In [2]:
import numpy as np

In [21]:
# array creation function
zeros  = np.zeros(5)
zeros_2d = np.zeros((2,5))

ones =np.ones(2)
ones_2d = np.ones((2,3))

empty = np.empty(2)
empty_2d = np.empty((2,2))

full = np.full(5,5)
const_2d = np.full((2,3),5)

arange = np.arange(10)
arange2 = np.arange(2,10,2)

print(zeros)
print(zeros_2d)
print(ones)
print(ones_2d)
print(empty)
print(empty_2d)
print(full)
print(const_2d)
print(arange)
print(arange2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1.]
[[0.00000000e+000 9.34562187e-312]
 [9.34562188e-312 9.34562188e-312]]
[5 5 5 5 5]
[[5 5 5]
 [5 5 5]]
[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [24]:
# specific data type
arr = np.array([1,2,3])
print(arr.dtype)

arr_float = np.array([1,2.3,3],dtype=np.float32)
arr_int = np.array([1.2,3.5,4],dtype=np.int32)

print(arr_float)
print(arr_int)

int64
[1.  2.3 3. ]
[1 3 4]


In [31]:
# array atributes

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

(3, 4)
2
12
int64
8
96


In [36]:
arr = np.arange(12)

arr_2d = arr.reshape(3,4)

arr_3d = arr.reshape(2,2,3)

arr_auto = arr.reshape(3,-1)

flat = arr_3d.flatten()
flat1 = arr_2d.ravel()

transposed = arr_2d.T


print(arr)
print(arr_2d)
print(arr_3d)
print(arr_auto)
print(flat)
print(flat1)
print(transposed)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [38]:
# array indexing and slicing

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])     
print(arr[-1])   


print(arr[1:4])  
print(arr[:3])   
print(arr[2:])    
print(arr[::2])   
print(arr[::-1])  


arr[0] = 100
arr[1:3] = [200, 300]
print(arr)

10
50
[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]
[100 200 300  40  50]


In [39]:
# multi dimentional indexing
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d[0, 0])    
print(arr_2d[1, 2])    
print(arr_2d[-1, -1])


print(arr_2d[0])       
print(arr_2d[0, :])    


print(arr_2d[:, 0])   


print(arr_2d[0:2, 1:3])


print(arr_2d[::2, ::2])

1
6
9
[1 2 3]
[1 2 3]
[1 4 7]
[[2 3]
 [5 6]]
[[1 3]
 [7 9]]


In [40]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print(arr1 > 3)
print(arr1 == 3) 

[False False False  True  True]
[False False  True False False]


In [41]:
arr = np.array([1, 4, 9, 16, 25])

# Mathematical functions
print(np.sqrt(arr))        
print(np.square(arr))     
print(np.abs([-1, -2, 3])) 
print(np.exp(arr))       
print(np.log(arr))         
print(np.log10(arr))       

# Trigonometric
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))     
print(np.cos(angles))      
print(np.tan(angles))     

# Rounding
arr = np.array([1.2, 2.5, 3.7, 4.9])
print(np.round(arr))      
print(np.floor(arr))      
print(np.ceil(arr))       

# Element-wise comparison
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 5, 2])
print(np.maximum(arr1, arr2))  
print(np.minimum(arr1, arr2)) 

[1. 2. 3. 4. 5.]
[  1  16  81 256 625]
[1 2 3]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[0.         0.60205999 0.95424251 1.20411998 1.39794001]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[1. 2. 4. 5.]
[1. 2. 3. 4.]
[2. 3. 4. 5.]
[1 5 3]
[1 2 2]


In [43]:
# Broadcasting
arr1 = np.array([[1], [2], [3]])      # (3, 1)
arr2 = np.array([[10, 20, 30, 40]])   # (1, 4)
result = arr1 + arr2  
result 

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

In [44]:
"""
Day 8: Introduction to NumPy - Comprehensive Practice Notebook

This notebook demonstrates:
1. Array creation and manipulation
2. Indexing and slicing
3. Vectorized operations
4. Broadcasting
5. Aggregations and statistics
6. Practical numerical computations

Author: Python Student
Date: 2025
"""

import numpy as np
import time

print("NumPy version:", np.__version__)

# ============================================
# SECTION 1: Array Creation
# ============================================
print("\n" + "="*80)
print("SECTION 1: ARRAY CREATION")
print("="*80)

# From Python lists
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)
print(f"\n1D Array from list: {array_1d}")
print(f"   Shape: {array_1d.shape}, Dtype: {array_1d.dtype}")

# 2D array
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(list_2d)
print(f"\n2D Array from nested list:\n{array_2d}")
print(f"   Shape: {array_2d.shape}, Dtype: {array_2d.dtype}")

# Creation functions
print("\nZeros array:")
zeros = np.zeros((3, 4))
print(zeros)

print("\nOnes array:")
ones = np.ones((2, 5))
print(ones)

print("\nFull array (filled with 7):")
sevens = np.full((3, 3), 7)
print(sevens)

print("\nRange array (like Python range):")
range_arr = np.arange(0, 20, 2)  # Start, stop, step
print(range_arr)

print("\nLinear spacing (10 points from 0 to 1):")
linspace_arr = np.linspace(0, 1, 10)
print(linspace_arr)

print("\nIdentity matrix (3x3):")
identity = np.eye(3)
print(identity)

print("\nRandom array (5 values between 0 and 1):")
random_arr = np.random.rand(5)
print(random_arr)

print("\nRandom integers (10 values between 1 and 100):")
random_ints = np.random.randint(1, 101, 10)
print(random_ints)


# ============================================
# SECTION 2: Array Attributes and Reshaping
# ============================================
print("\n" + "="*80)
print("SECTION 2: ARRAY ATTRIBUTES AND RESHAPING")
print("="*80)

arr = np.arange(24)
print(f"\nOriginal 1D array: {arr}")
print(f"   Shape: {arr.shape}")
print(f"   Dimensions (ndim): {arr.ndim}")
print(f"   Size (total elements): {arr.size}")
print(f"   Data type: {arr.dtype}")
print(f"   Item size: {arr.itemsize} bytes")
print(f"   Total bytes: {arr.nbytes} bytes")

# Reshape to 2D
arr_2d = arr.reshape(4, 6)
print(f"\nReshaped to 2D (4x6):\n{arr_2d}")

# Reshape to 3D
arr_3d = arr.reshape(2, 3, 4)
print(f"\nReshaped to 3D (2x3x4):\n{arr_3d}")

# Transpose
transposed = arr_2d.T
print(f"\nTransposed (6x4):\n{transposed}")

# Flatten
flattened = arr_3d.flatten()
print(f"\nFlattened back to 1D: {flattened}")


# ============================================
# SECTION 3: Indexing and Slicing
# ============================================
print("\n" + "="*80)
print("SECTION 3: INDEXING AND SLICING")
print("="*80)

# 1D indexing
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"\nOriginal array: {arr}")
print(f"First element (index 0): {arr[0]}")
print(f"Last element (index -1): {arr[-1]}")
print(f"Slice [2:5]: {arr[2:5]}")
print(f"Every 2nd element: {arr[::2]}")
print(f"Reversed: {arr[::-1]}")

# 2D indexing
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(f"\n2D Array:\n{arr_2d}")
print(f"Element at row 1, col 2: {arr_2d[1, 2]}")
print(f"First row: {arr_2d[0]}")
print(f"First column: {arr_2d[:, 0]}")
print(f"Subarray [0:2, 1:3]:\n{arr_2d[0:2, 1:3]}")

# Boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"\nOriginal array: {arr}")
print(f"Elements > 5: {arr[arr > 5]}")
print(f"Even numbers: {arr[arr % 2 == 0]}")
print(f"Elements between 3 and 7: {arr[(arr > 3) & (arr < 7)]}")

# Fancy indexing
indices = [0, 2, 4, 6]
print(f"Elements at indices {indices}: {arr[indices]}")


# ============================================
# SECTION 4: Vectorized Operations
# ============================================
print("\n" + "="*80)
print("SECTION 4: VECTORIZED OPERATIONS")
print("="*80)

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

print(f"\nArray 1: {arr1}")
print(f"Array 2: {arr2}")

print(f"\nAddition: {arr1 + arr2}")
print(f"Subtraction: {arr1 - arr2}")
print(f"Multiplication: {arr1 * arr2}")
print(f"Division: {arr1 / arr2}")
print(f"Power: {arr1 ** 2}")

# Scalar operations
print(f"\nArray + 10: {arr1 + 10}")
print(f"Array * 3: {arr1 * 3}")
print(f"Array ** 0.5: {arr1 ** 0.5}")

# Universal functions
arr = np.array([1, 4, 9, 16, 25])
print(f"\nArray: {arr}")
print(f"Square root: {np.sqrt(arr)}")
print(f"Exponential: {np.exp(arr)}")
print(f"Natural log: {np.log(arr)}")

# Trigonometric functions
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print(f"\nAngles (radians): {angles}")
print(f"Sine: {np.sin(angles)}")
print(f"Cosine: {np.cos(angles)}")

# Performance comparison: NumPy vs Python lists
print("\n--- PERFORMANCE COMPARISON ---")
size = 1000000

# Python list
python_list = list(range(size))
start = time.time()
result_list = [x * 2 for x in python_list]
list_time = time.time() - start

# NumPy array
numpy_array = np.arange(size)
start = time.time()
result_numpy = numpy_array * 2
numpy_time = time.time() - start

print(f"Python list time: {list_time:.4f} seconds")
print(f"NumPy array time: {numpy_time:.4f} seconds")
print(f"NumPy is {list_time/numpy_time:.1f}x faster!")


# ============================================
# SECTION 5: Broadcasting
# ============================================
print("\n" + "="*80)
print("SECTION 5: BROADCASTING")
print("="*80)

# Scalar broadcasting
arr = np.array([1, 2, 3, 4, 5])
print(f"\nArray: {arr}")
print(f"Array + 10 (scalar broadcast): {arr + 10}")

# 1D + 2D broadcasting
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[10],
                   [20],
                   [30]])

print(f"\n1D array (shape {arr_1d.shape}): {arr_1d}")
print(f"2D array (shape {arr_2d.shape}):\n{arr_2d}")

result = arr_1d + arr_2d
print(f"\nBroadcasted addition (shape {result.shape}):\n{result}")

# More complex broadcasting
arr1 = np.arange(3).reshape(3, 1)  # (3, 1)
arr2 = np.arange(4).reshape(1, 4)  # (1, 4)

print(f"\nArray 1 (shape {arr1.shape}):\n{arr1}")
print(f"Array 2 (shape {arr2.shape}):\n{arr2}")

result = arr1 + arr2  # (3, 4)
print(f"\nBroadcasted result (shape {result.shape}):\n{result}")


# ============================================
# SECTION 6: Aggregations and Statistics
# ============================================
print("\n" + "="*80)
print("SECTION 6: AGGREGATIONS AND STATISTICS")
print("="*80)

arr = np.array([2, 5, 1, 8, 3, 9, 4, 7, 6, 10])
print(f"\nArray: {arr}")

print(f"\nSum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr):.2f}")
print(f"Variance: {np.var(arr):.2f}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Range: {np.ptp(arr)}")  # Peak-to-peak

# Index of min/max
print(f"\nIndex of min: {np.argmin(arr)}")
print(f"Index of max: {np.argmax(arr)}")

# Cumulative operations
print(f"\nCumulative sum: {np.cumsum(arr)}")

# 2D aggregations
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(f"\n2D Array:\n{arr_2d}")

print(f"\nTotal sum: {np.sum(arr_2d)}")
print(f"Sum along axis 0 (columns): {np.sum(arr_2d, axis=0)}")
print(f"Sum along axis 1 (rows): {np.sum(arr_2d, axis=1)}")

print(f"\nMean of each column: {np.mean(arr_2d, axis=0)}")
print(f"Mean of each row: {np.mean(arr_2d, axis=1)}")

print(f"\nMax of each column: {np.max(arr_2d, axis=0)}")
print(f"Min of each row: {np.min(arr_2d, axis=1)}")


# ============================================
# SECTION 7: Practical Computation Example
# ============================================
print("\n" + "="*80)
print("SECTION 7: PRACTICAL COMPUTATION - DATA NORMALIZATION")
print("="*80)

# Generate sample data (student test scores)
np.random.seed(42)  # For reproducibility
scores = np.random.randint(50, 100, size=(10, 5))  # 10 students, 5 tests

print("\nOriginal Scores (10 students × 5 tests):")
print(scores)

# Calculate statistics
print("\n--- STATISTICS ---")
print(f"Mean score per test: {np.mean(scores, axis=0)}")
print(f"Mean score per student: {np.mean(scores, axis=1)}")
print(f"Overall mean: {np.mean(scores):.2f}")
print(f"Overall std dev: {np.std(scores):.2f}")

# Find best and worst performers
student_averages = np.mean(scores, axis=1)
best_student = np.argmax(student_averages)
worst_student = np.argmin(student_averages)

print(f"\nBest student: Student {best_student} (avg: {student_averages[best_student]:.2f})")
print(f"Worst student: Student {worst_student} (avg: {student_averages[worst_student]:.2f})")

# Normalize scores (z-score normalization)
mean = np.mean(scores)
std = np.std(scores)
normalized_scores = (scores - mean) / std

print("\nNormalized Scores (z-scores):")
print(normalized_scores.round(2))

# Identify outliers (|z-score| > 2)
outliers = np.abs(normalized_scores) > 2
print(f"\nNumber of outlier scores: {np.sum(outliers)}")


# ============================================
# SECTION 8: Matrix Operations
# ============================================
print("\n" + "="*80)
print("SECTION 8: MATRIX OPERATIONS")
print("="*80)

# Matrix multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Element-wise multiplication
print("\nElement-wise multiplication (A * B):")
print(A * B)

# Matrix multiplication (dot product)
print("\nMatrix multiplication (A @ B or np.dot(A, B)):")
print(A @ B)  # Python 3.5+
# Or: print(np.dot(A, B))

# Transpose
print("\nTranspose of A:")
print(A.T)

# Determinant
print(f"\nDeterminant of A: {np.linalg.det(A):.2f}")

# Inverse
print("\nInverse of A:")
print(np.linalg.inv(A))

# Verify: A @ A_inv = Identity
A_inv = np.linalg.inv(A)
identity_check = A @ A_inv
print("\nA @ A^(-1) (should be identity):")
print(identity_check.round(10))  # Round to remove floating point errors


# ============================================
# SECTION 9: Advanced Example - Moving Average
# ============================================
print("\n" + "="*80)
print("SECTION 9: PRACTICAL EXAMPLE - MOVING AVERAGE")
print("="*80)

# Simulate stock prices
np.random.seed(42)
days = 30
prices = 100 + np.cumsum(np.random.randn(days))  # Random walk

print(f"Stock prices for {days} days:")
print(prices.round(2))

# Calculate 5-day moving average
window = 5
moving_avg = np.convolve(prices, np.ones(window)/window, mode='valid')

print(f"\n5-day moving average:")
print(moving_avg.round(2))

# Find days with largest price changes
price_changes = np.diff(prices)
largest_gain_day = np.argmax(price_changes) + 1
largest_loss_day = np.argmin(price_changes) + 1

print(f"\nLargest gain: Day {largest_gain_day} (+${price_changes[largest_gain_day-1]:.2f})")
print(f"Largest loss: Day {largest_loss_day} (-${abs(price_changes[largest_loss_day-1]):.2f})")

# Volatility (standard deviation of returns)
returns = price_changes / prices[:-1]
volatility = np.std(returns) * 100
print(f"\nVolatility (std dev of returns): {volatility:.2f}%")


# ============================================
# SECTION 10: Summary and Best Practices
# ============================================
print("\n" + "="*80)
print("SECTION 10: KEY TAKEAWAYS")
print("="*80)

print("""
1. NumPy arrays are MUCH faster than Python lists for numerical operations
2. Use vectorized operations instead of loops whenever possible
3. Broadcasting enables operations on arrays of different shapes
4. axis=0 operates along rows (down columns), axis=1 along columns (across rows)
5. Boolean indexing is powerful for filtering data
6. NumPy functions are optimized and written in C
7. Always specify dtype when memory or precision matters
8. Use np.random.seed() for reproducible random numbers
9. Matrix operations: @ for multiplication, .T for transpose
10. NumPy is the foundation for pandas, scikit-learn, and most scientific Python libraries
""")

print("\n" + "="*80)
print("NOTEBOOK COMPLETE!")
print("="*80)

NumPy version: 2.3.3

SECTION 1: ARRAY CREATION

1D Array from list: [1 2 3 4 5]
   Shape: (5,), Dtype: int64

2D Array from nested list:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
   Shape: (3, 3), Dtype: int64

Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Full array (filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Range array (like Python range):
[ 0  2  4  6  8 10 12 14 16 18]

Linear spacing (10 points from 0 to 1):
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array (5 values between 0 and 1):
[0.76768604 0.71755333 0.78395115 0.77953058 0.75083465]

Random integers (10 values between 1 and 100):
[95 22 29 82 59 24  1 31 78 18]

SECTION 2: ARRAY ATTRIBUTES AND RESHAPING

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
   Shape: (24,)
   Dimensions (ndim): 1